{
    'name': 'FTS Customizations',
    'version': '1.0',
    'category': 'Hidden',
    'description': """
    """,
    'author': 'Strategic Dimensions,
    'website': 'http://www.openerp.com',
    'images': [''],
    'depends': [ 'mail', 'base', 'crm','purchase','base_setup','website_quote'],
    'data': [
  	"security/fts_groups.xml",
	"views/crm_lead_view.xml",
	"views/templates.xml",
	"views/sale_view.xml",
	"views/purchase_config_settings_view.xml",
	"views/purchase_order_view.xml",
	"views/stock_view.xml",
	"views/stock_quant_view.xml",
	"views/product_view.xml",
	"views/account_statement_report.xml",
	"security/fts_security.xml",
	"report/purchase_order_templates.xml",
	"report/invoice_report_templates.xml",
        "report/sale_report_templates.xml",
	"report/stock_report_deliveryslip.xml",
    ],
    'qweb':['static/src/xml/base.xml',],
    'demo': [],
    'test':[],
    'installable': True,
    'auto_install': False,
}
